DROP TABLE IF EXISTS GROUPDETAIL;
CREATE TABLE GROUPDETAIL(
    ID INT PRIMARY KEY NOT NULL,
    CHN VARCHAR(10),
    LIBRARYNAME1 VARCHAR(64),
    LIBRARYNAME2 VARCHAR(64),
    FEATUREID VARCHAR(64),
    PEOPLEID VARCHAR(64),
    CATEGORY VARCHAR(64),
    X INT,
    Y INT
)